# web端口
server:
  port: 8010

# mybatis的mapper文件路径
mybatis:
  mapper-locations: classpath:mapping/*.xml

# 配置数据库连接等数据源
spring:
  datasource:
    name: dianping
    url: jdbc:mysql://127.0.0.1:3306/dianping?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    # 使用druid做连接池管理
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver